### ISSUE TITLE
Implement renderInsert for Oracle

### ISSUE THREAD

**Issue by jczuchnowski** [zio/zio-sql#155]

**Comment by peixunzhang** [comment]
I will take this ticket.

**Comment by baldram** [comment]
Hey @peixunzhang, to avoid conflicts, you might be interested in aligning your branch to the latest state of the master.
In [this change](https://github.com/zio/zio-sql/pull/700/files) I renamed the Spec file where your tests are supposed to go.
Current name is `OracleSqlModuleSpec.scala` instead of `OracleSqlModuleSpec.scala`. Best regards!

**Comment by jczuchnowski** [comment]
Done in https://github.com/zio/zio-sql/pull/695
