### ISSUE TITLE
Add 'scale' function to PostgresModule

### ISSUE THREAD

**Issue by jczuchnowski** [zio/zio-sql#176]
Add support for function `scale` described in the PostgreSQL [docs](https://www.postgresql.org/docs/current/functions-math.html).
1. Add function to `PostgresFunctionDef` in `PostgresModule`
2. Add test in `FunctionDefSpec`

**Comment by Porcupine96** [comment]
Hi, how should this one behave?

In Postgres `select scale(8.4100)` would return `4`. 

However in Scala if we were to run `Scale(8.4100)`, `8.4100` would be truncated to `8.41` and the call would return `2`. 
Do you think this behavior is acceptable or maybe should we define `Scale` as a function that takes a String instead of a Double?

**Comment by jczuchnowski** [comment]
This doesn't seem to be a useful function.
